### ISSUE TITLE
option to return only base filenames instead of whole filepath?

### ISSUE THREAD

**Issue by lpappone** [jergason/recursive-readdir#10]
Would you be interested in adding an option to return an array including only the base filenames instead of the entire filepath?

**Comment by ldong** [comment]
Maybe you can do an iteration of array of `filepath`s , then filter them using the following

```js
var path = require('path');
path.basename(YOUR_PATH_VARIABLE);
```

**Comment by jergason** [comment]
I'd prefer to keep this out of the core module. Thank you for suggesting it though!
