### ISSUE TITLE
Negative matches do not enter folders failing the match

### ISSUE THREAD

**Issue by olingerc** [jergason/recursive-readdir#16]
I'm using recursive-readdir to get a list of files with a specific extension. I use '!*txt*' as macth. This causes folders not having 'txt' in their name to be ignored.
I was a bit surprised by this behaviour, maybe it should be documented, or the match should only be applied to files and not folders.

**Comment by ferhatelmas** [comment]
:+1: I also hit the same problem. if negated ignore is given, subdirectories are neglected.

**Comment by jergason** [comment]
Okay, I'll look in to this more.

**Comment by ferhatelmas** [comment]
I'm just started working with node but I can give a try if you wish.

**Comment by jergason** [comment]
@ferhatelmas Please do!

**Comment by Ajedi32** [comment]
Fyi you shouldn't use `!txt` to match all non-text files. `!*.txt` would be the appropriate matcher for that.

Also, this change has some potentially undesirable effects. I made a few comments regarding that in e2f2ea0a3d3e35a4f0348826457f40d5d37f383d.

**Comment by Ajedi32** [comment]
Your point about negative matchers causing havoc with directories is a good one though. Hmm...
