### ISSUE TITLE
Doesn't preserve order of files

### ISSUE THREAD

**Issue by abbr** [jergason/recursive-readdir#17]
In a project I am working on, after lengthy troubleshooting, I finally found that *recursive-readdir* doesn't yield consistent ordering of files by file name. Even though it's not an advertised feature, I think at least it should be documented that order is not guaranteed. Also, implementing the feature shouldn't be hard.

**Comment by jergason** [comment]
closed by 056fc60107f3207d844eef6b6823f1cb61420e0e
