### ISSUE TITLE
Make ignores resolve relative to the path passed to recursive-readdir

### ISSUE THREAD

**Issue by Ajedi32** [jergason/recursive-readdir#23]
If I pass an absolute path to `recursive-readdir`

```javascript
readdir = require('recursive-readdir')
readdir("/home/ajedi32/some_dir", function(e, l){ console.log(l); })
```

and I want to ignore a specific file in a subdirectory of that path, like `/home/ajedi32/some_dir/folder/file.txt`, then I should be able to specify the ignore as `"folder/file.txt"`. The full path of `"/home/ajedi32/some_dir/folder/file.txt"` shouldn't be required.

**Comment by rstacruz** [comment]
:+1: would love to see this, as well as a way to distinguish directories and files to be ignored.

**Comment by jergason** [comment]
@rstacruz what do you mean "a way to distinguish directories and files"?

**Comment by jergason** [comment]
@Ajedi32 this can be accomplished by a globstar pattern:

```JavaScript
var readdir = require('recursive-readdir')
var ignores = ['**/folder/file.txt']
readdir("/home/ajedi32/some_dir", ignores, function(e, l){ console.log(l); })
```

Is there a reason this won't work for you?

**Comment by Ajedi32** [comment]
@rstacruz As of e2f2ea0a3d3e35a4f0348826457f40d5d37f383d (unreleased), you can't ignore directories at all, so that problem is basically solved.

**Comment by Ajedi32** [comment]
@jergason Personally I think that rather unintuitive. If I'm passing a path to ignore, obviously I want that path to be relative to the directory I'm reading, since ignoring a file outside the directory I'm reading would be pointless.

Aside from that though, what you suggested there wouldn't work in all cases. Consider the following directory structure:

```text
├── somefile.txt
├── example
│   ├── ignore_this.html
│   └── ignore_this.md
└── subdir
     └── example
         ├── don't_ignore_this.md
         └── don't_ignore_this.html
```

What if I want to ignore everything in `example`, but not `subdir/example`, and I want to avoid specifying an absolute path? I'd expect `["example/"]` or `["example/**"]` to accomplish that, but they don't. Your example of `["**/example/"]` also wouldn't work, since it would ignore everything in `subdir/example`, which isn't what I want.

Note that this issue is primarily motivated by some downstream issues with Metalsmith, where the need for ignores to be relative to the directory being read is even more obvious. We could of course fix that problem in Metalsmith by implementing our own separate ignore system instead of using the built-in method in this library, but I thought I'd bring it up here first since IMO this seems like like unintuitive behavior from `recursive-readdir`.

**Comment by jergason** [comment]
I'm not sure it is intuitive that passing `["example/"]` to ignore would ignore things in `example` but not in `subdir/example`. How is there enough information in the pattern to tell which `example` directory you actually want to ignore?

**Comment by Ajedi32** [comment]
@jergason Ah, that's a good point. Maybe `./example/`?

Or maybe `/example/`? That's  [how `git` does it](http://stackoverflow.com/q/3637660/1157054) anyway.

**Comment by jergason** [comment]
@Ajedi32 does #28 solve this?

**Comment by Ajedi32** [comment]
@jergason Kind of. It resolves my immediate problem by allowing me to get the behavior I want by just ignoring `recursive-readdir`'s string-based ignores entirely and writing my own code to convert ignore strings into matcher functions.

Overall though, I still think having these ignore strings be relative to the directory being read is more intuitive behavior than what recursive-readdir currently does.

Maybe leave it open pending feedback from other users of the project? Or close it for now and reopen if someone in the future has a similar problem? Either way is fine by me.
