### ISSUE TITLE
Multiple negated ignores

### ISSUE THREAD

**Issue by rstacruz** [jergason/recursive-readdir#24]
This setup will not match anything:

```js
ignore: [
  '*',
  '!readme.md',
  '!history.md'
]
```

this will work in a `.gitignore` though, because `!` rules only negate anything matched previously.

**Comment by jergason** [comment]
@rstacruz We just use [minimatch](https://github.com/isaacs/minimatch) for ignores, which doesn't support this functionality as far as I know. Replicating the `.gitignore` semantics isn't something this library is trying to accomplish.
