### ISSUE TITLE
Feature request: Ability to pass a function to ignore

### ISSUE THREAD

**Issue by Ajedi32** [jergason/recursive-readdir#25]
To make the current system for ignoring files much more powerful, it would be great if we could pass a function to ignore instead of just minimatch strings. The function would take in the file path and lstat object, and return true to ignore the file, or false to keep it.

This would add a lot of power to `recursive-readdir`'s ignore system, addressing both the use cases of #14 and my comments on e2f2ea0a3d3e35a4f0348826457f40d5d37f383d in one fell swoop. It would also really help with some of the problems we've discussed in #23.

**Comment by Ajedi32** [comment]
Also, just to note: I'm willing to contribute a PR here if you think this is a feature you'd be willing to add.

**Comment by jergason** [comment]
This would be fantastic. I'm a bit wary of complicating a dirt-simple module by trying to support more complex ignoring behaviors, and as you can see I've already added some wonkiness trying to do so.

**Comment by Ajedi32** [comment]
Awesome. I'll look into this and probably submit a PR over the weekend. Seems like it should be pretty straightforward to implement.
