### ISSUE TITLE
How to ignore protected files during the reading ?

### ISSUE THREAD

**Issue by kevincaradant** [jergason/recursive-readdir#46]
Hi

In the moment when I get an error ( Error: EPERM: operation not permitted, stat 'F:\System Volume Information' ), Files I can't get all others files which are OK.

Is it a way to force to continue to analyze or a way to check after each file what to do ? 

Thank you 

NB: maybe my question is stupid but in fact, I'm sticked with my idea, I don't know how to get a workaround. Of course I can create again the stuff at the hand  but it's not my aim.

OK this: https://github.com/jergason/recursive-readdir/pull/43 seems near that I want

**Comment by kevincaradant** [comment]
@popod , I tried your repository because I get this issue: #46, but I get this error:

TypeError: ignores.map is not a function.

I made:

```
        recursiveRead(argv.path, {'forceContinue': true}, (err, files) => {
          filesPath = files;
        });
```


Do you see an error from me ? 

thank you

**Comment by popod** [comment]
Hi,

`recursive(path, {'forceContinue': true}, function (err, files) {}` works for me.

If you try to add normal files or broken links, does it works ?

**Comment by kevincaradant** [comment]
Hi

Ok my bad..., your work is perfect! You developped the feature on the patch-2 branch and not on the master so in the package.json , I forgot to add `#patch-2` at the en dof the git url :). Before, I loaded the same version that the initial repository.

Thank you, your answer think to me to check this.

**Comment by popod** [comment]
Oh yes ! sorry my bad.. I hope my PR will be merged with this repo so we could use the original recursive-readdir module.

**Comment by kevincaradant** [comment]
Yes,  for the moment I will fork your staff,  and keep like that and if one day @jergason you will decide to merge it.  Tell me.  Thank you  ')

**Comment by josephj** [comment]
The same situation could be easily reproducible with an NTFS disk. It always has a `System Volume Information` which is access denied. Unfortunately, the current recursive-readdir doesn't seem to have any way to work around it 😢

**Comment by popod** [comment]
@josephj #43 could perhaps helps you ?

**Comment by josephj** [comment]
@popod yea thanks I have integrated your patch successfully. working good. thanks mate.
