### ISSUE TITLE
Ignore files doesnt work

### ISSUE THREAD

**Issue by JKasyan** [jergason/recursive-readdir#54]
`recursive("src/aura", ['.css', '.xml'], function(err, files) {
console.log(files)
}`

When I read files I anywhere see filed css and xml files

**Comment by jergason** [comment]
The ignore argument takes an array of `minimatch` strings. They are basically shell glob-style patterns. You need to change your array to `['*.css', '*.xml']`.

**Comment by JKasyan** [comment]
Yes it is help me. Thank you.
Sorry for disturbing.
