### ISSUE TITLE
README contains incorrect?

### ISSUE THREAD

**Issue by kthjm** [jergason/recursive-readdir#55]
Hi, thanks helpful package. This is so tiny report but I would like to suggest modify README.

README says:
```js
recursive("some/path", function (err, files) {
  // `files` is an array of absolute file paths
  console.log(files);
});
```
but [path.join()](https://nodejs.org/api/path.html#path_path_join_paths) doesn't resolve paths into an absolute path.
https://github.com/jergason/recursive-readdir/blob/bbd426243481c9ab9d2743b51b5dd9b637a2a699/index.js#L54
So if dirpath as argument is relative, the result paths are relative too.
thanks :)

**Comment by jergason** [comment]
Fixed by 854399da2ce671cd201bc4ec5098bb6b3f4a9112
