### ISSUE TITLE
TypeError: fs.readdir is not a function

### ISSUE THREAD

**Issue by Gajendra28121996** [jergason/recursive-readdir#74]
In React App I can't access fs module. I want to list down the file's address in an array.

**Comment by zanonnicola** [comment]
@Gajendra28121996  The `fs` module is not available in the browser. It works only in Node.js.

**Comment by Gajendra28121996** [comment]
I have a text ( which is auto-generated in every 1hr) where I have a list of CCTV recording files. i just want to play all without giving a hardcoded require in my app. Because video files are actively generated as it saves into the machine and react app do 'not aware of new files in the directory!

**Comment by zanonnicola** [comment]
I think this question might be better asked on StackOverflow. I don't think it really related to this module.

**Comment by Gajendra28121996** [comment]
Ok thanks for the help
